#!/usr/bin/env bash
# check-roadmap-fresh.sh — pre-commit: ROADMAP.md is a generated projection
# (scripts/roadmap-render.sh); this checker blocks a commit that carries a
# stale one — hand-edited after generation, or drifted from its source epics
# dir. Freshness = re-render to a temp file and diff against the committed
# ROADMAP.md; any difference is stale (AC-11 — this replaces the retired
# status-drift audit, which a generated table cannot suffer by construction).
#
# root = TOUCHSTONE_CHECK_ROOT (rail-loop / fixture mode) else the repo's own
# toplevel. No ROADMAP.md, or no <root>/.touchstone/epics -- nothing to
# check, exit 0. A ROADMAP.md with no generated header is the pre-migration
# hand-written form -- grandfathered, exit 0 with a one-line note, never
# reimplements status-drift on it. Absent python3 -- exit 0 with a note on
# stderr (this checker still hard-blocks a real staleness finding; it does
# not belong to the always-exit-0 warn class of checker).
set -uo pipefail

root="${TOUCHSTONE_CHECK_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null)}" || exit 0
[ -n "$root" ] || exit 0

out_file="$root/ROADMAP.md"
[ -f "$out_file" ] || exit 0
[ -d "$root/.touchstone/epics" ] || exit 0

if ! grep -q 'GENERATED by scripts/roadmap-render.sh' "$out_file"; then
  echo "[check-roadmap-fresh] $out_file: hand-written (pre-migration) — not checked"
  exit 0
fi

# roadmap-render.sh is a committed script, never duplicated into a fixture
# tree — locate it in the repo this checker itself ships from (mirrors
# check-plugin-graph.sh), so a fixture run under TOUCHSTONE_CHECK_ROOT still
# finds the real renderer.
self_dir="$(cd "$(dirname "$0")" 2>/dev/null && pwd)"
self_root="$(git -C "${self_dir:-.}" rev-parse --show-toplevel 2>/dev/null)"
[ -n "$self_root" ] || exit 0
renderer="$self_root/scripts/roadmap-render.sh"
[ -f "$renderer" ] || exit 0

command -v python3 >/dev/null 2>&1 || {
  echo "[check-roadmap-fresh] WARN: python3 not found -- freshness check skipped" >&2
  exit 0
}

# the re-render must land beside $out_file (same dir as $root) so the
# rendered "Epic" column's relative links match the original -- a tmp file
# elsewhere would make every link differ and false-trip every tree.
tmp="$(mktemp "$root/.roadmap-fresh-check.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

if ! bash "$renderer" --root "$root" --out "$tmp" >/dev/null 2>&1; then
  echo "[check-roadmap-fresh] re-render of $out_file failed"
  exit 1
fi

if ! diff -q "$out_file" "$tmp" >/dev/null 2>&1; then
  echo "[check-roadmap-fresh] $out_file: stale — differs from a fresh re-render (regenerate via scripts/roadmap-render.sh)"
  exit 1
fi

exit 0
