#!/usr/bin/env bash
# scripts/tests-smoke/probe-anvil.sh — headless invoke-and-observe probe for anvil's own
# behaviour ACs. Self-build only: it spends real model tokens (a `claude -p` session that
# runs /touchstone:anvil on a fixture project), so the smoke suite runs only `--self-test`.
#
#   probe-anvil.sh run --fixture <project-dir> --plugin-dir <checkout> --out <evidence-dir>
#                      [--model <alias>] [--delete-freeze] [--agent-override <ruler-author.md>]
#                      [--dirty <rel-path>] [--extra-prompt <text>] [--max-budget-usd <n>]
#                      [--max-turns <n>] [--keep]
#       copies the fixture project to a scratch git repo (one pre-build commit), runs
#       `claude -p "/touchstone:anvil <spec>" --plugin-dir <checkout>` there with an observer
#       PostToolUse hook, and leaves under <evidence-dir>: command.txt, plugin_revision.txt
#       (the checkout's HEAD sha, then `tree: clean` or `tree: dirty` over the shipped
#       surface), started_at.txt (ISO-8601 UTC), output.log (the stream-json transcript),
#       events.jsonl (one line per tool call: seq, tool, agent, model, prompt markers,
#       ruler/freeze/verdict/disputes presence, W-n count in the spec, dirty source paths),
#       artifacts/ (the epic's build/ files, spec and deviation.yaml as left), final-status.txt,
#       cost.txt.
#       --delete-freeze: the observer deletes build/freeze.json the first time it sees it
#       (the halt shape). --agent-override: the plugin is a detached worktree of <checkout>
#       with agents/ruler-author.md replaced; plugin_revision.txt gains an `override:` line.
#       --dirty: the named tracked file (created if absent) is left dirty before the run.
#       --extra-prompt: text appended to the prompt after the anvil command.
#   probe-anvil.sh verify <evidence-dir> --expect <mode> [--plugin-dir <checkout>]
#       order        ruler.yaml appeared before freeze.json, freeze.json before any source
#                    edit, verdict.yaml exists, and (with --plugin-dir) plugin_revision.txt
#                    is its HEAD or an ancestor, with `tree: clean`. Exit 1 names the
#                    artifact out of order.
#       halt-freeze  freeze.json was deleted, no source path edited afterwards, no
#                    verdict.yaml, output.log names freeze.json.
#       silent-once  exactly two ruler-author dispatches; ruler.yaml and freeze.json present.
#       invalid-once exactly two dispatches, the second prompt carrying check-artifact
#                    output; ruler.yaml and freeze.json present.
#       silent-twice exactly two dispatches, no freeze.json, output.log names ruler.yaml.
#       overreach    deviation.yaml carries a D-n naming the overreaching path and records the
#                    ruler discarded, at most two dispatches; a second violation halts (no
#                    freeze.json), a clean second dispatch continues to freeze.
#       ambiguous    the spec's waiting_on_human gained a W-n naming AC-7, freeze.json exists,
#                    deviation.yaml carries a blocked D-n naming AC-7, verdict.yaml carries
#                    AC-7 UNVERIFIED with reason ambiguous.
#       guard        output.log carries the guard hook's message (`guard-ruler:` … `is frozen`)
#                    and verdict.yaml has sha_check ok.
#   probe-anvil.sh --self-test
#       two canned evidence trees — valid order, and a source edit before freeze — must
#       verify as exit 0 and exit 1 naming the out-of-order artifact.
#
# Source paths = the spec's touch_set.touched entries (read with python3 + PyYAML). The
# observer records `git status --porcelain` limited to those paths after every tool call;
# the first non-empty record is the first source edit.
# exit 0 ok · 1 a named verification failure · 2 usage / missing dependency
set -uo pipefail

usage() { sed -n '2,48p' "$0" | sed 's/^# \{0,1\}//'; exit 2; }

# ---------------------------------------------------------------- observer hook (generated)
write_observer() {  # <path> <project> <out> <spec-rel> <delete-freeze 0|1>
  cat >"$1" <<EOF
#!/usr/bin/env bash
# generated by probe-anvil.sh — PostToolUse observer; never blocks (exit 0 always)
set -u
PROJECT='$2'; OUT='$3'; SPEC='$4'; DELETE_FREEZE=$5
payload="\$(cat 2>/dev/null || true)"
tool="\$(printf '%s' "\$payload" | jq -r '.tool_name // empty' 2>/dev/null)"
agent="\$(printf '%s' "\$payload" | jq -r '.tool_input.subagent_type // empty' 2>/dev/null)"
desc="\$(printf '%s' "\$payload" | jq -r '.tool_input.description // empty' 2>/dev/null)"
model="\$(printf '%s' "\$payload" | jq -r '.tool_input.model // empty' 2>/dev/null)"
fpath="\$(printf '%s' "\$payload" | jq -r '.tool_input.file_path // empty' 2>/dev/null)"
prompt="\$(printf '%s' "\$payload" | jq -r '.tool_input.prompt // empty' 2>/dev/null)"
markers=""
case "\$prompt" in *"re-dispatch"*) markers="re-dispatch" ;; esac
case "\$prompt" in *"check-artifact"*|*"acs["*) markers="\${markers:+\$markers,}check-artifact" ;; esac
case "\$prompt" in *"rulings:"*) markers="\${markers:+\$markers,}rulings" ;; esac
epic="\$(dirname "\$PROJECT/\$SPEC")"
seq=\$(( \$(wc -l < "\$OUT/events.jsonl" 2>/dev/null || echo 0) + 1 ))
ruler=false; [ -f "\$epic/build/ruler.yaml" ] && ruler=true
freeze=false; [ -f "\$epic/build/freeze.json" ] && freeze=true
verdict=false; [ -f "\$epic/build/verdict.yaml" ] && verdict=true
disputes=false; [ -f "\$epic/build/disputes.yaml" ] && disputes=true
wn="\$(grep -c '^  *- *id: *W-' "\$PROJECT/\$SPEC" 2>/dev/null)"; wn="\${wn:-0}"; case "\$wn" in ''|*[!0-9]*) wn=0 ;; esac
deleted=false
if [ "\$DELETE_FREEZE" = 1 ] && [ "\$freeze" = true ] && [ ! -f "\$OUT/freeze-deleted" ]; then
  rm -f "\$epic/build/freeze.json"; : > "\$OUT/freeze-deleted"; deleted=true
fi
dirty="\$(cd "\$PROJECT" && git status --porcelain -- \$(cat "\$OUT/source-paths.txt" 2>/dev/null) 2>/dev/null | awk '{print \$2}' | paste -sd, -)"
jq -nc --argjson seq "\$seq" --arg tool "\$tool" --arg agent "\$agent" --arg desc "\$desc" --arg model "\$model" --arg fpath "\$fpath" --arg markers "\$markers" \\
  --argjson ruler \$ruler --argjson freeze \$freeze --argjson verdict \$verdict --argjson disputes \$disputes --argjson deleted \$deleted --argjson wn "\${wn:-0}" --arg dirty "\$dirty" \\
  '{seq:\$seq, tool:\$tool, agent:\$agent, description:\$desc, model:\$model, file_path:\$fpath, prompt_markers:(\$markers|split(",")|map(select(length>0))), ruler:\$ruler, freeze:\$freeze, verdict:\$verdict, disputes:\$disputes, freeze_deleted:\$deleted, spec_wn:\$wn, src_dirty:(\$dirty|split(",")|map(select(length>0)))}' >>"\$OUT/events.jsonl" 2>/dev/null
exit 0
EOF
  chmod +x "$1"
}

shipped_surface_dirty() {  # <checkout> → 0 when the shipped surface is dirty
  local list="$1/.touchstone/shipped-surface.txt" prefixes=()
  if [ -f "$list" ]; then
    while IFS= read -r line; do
      line="${line%%#*}"; line="$(printf '%s' "$line" | sed 's/[[:space:]]*$//')"
      [ -n "$line" ] && prefixes+=("$line")
    done <"$list"
  fi
  [ "${#prefixes[@]}" -gt 0 ] || prefixes=(skills agents commands hooks scripts .claude-plugin)
  [ -n "$(git -C "$1" status --porcelain --untracked-files=all -- "${prefixes[@]}" 2>/dev/null)" ]
}

# ---------------------------------------------------------------- run
cmd_run() {
  local fixture="" plugin="" out="" model="sonnet" delete_freeze=0 override="" dirty="" extra="" budget="15" turns="400" keep=0
  while [ $# -gt 0 ]; do
    case "$1" in
      --fixture) fixture="$2"; shift 2 ;;
      --plugin-dir) plugin="$2"; shift 2 ;;
      --out) out="$2"; shift 2 ;;
      --model) model="$2"; shift 2 ;;
      --delete-freeze) delete_freeze=1; shift ;;
      --agent-override) override="$2"; shift 2 ;;
      --dirty) dirty="$2"; shift 2 ;;
      --extra-prompt) extra="$2"; shift 2 ;;
      --max-budget-usd) budget="$2"; shift 2 ;;
      --max-turns) turns="$2"; shift 2 ;;
      --keep) keep=1; shift ;;
      *) usage ;;
    esac
  done
  [ -d "$fixture" ] && [ -d "$plugin" ] && [ -n "$out" ] || usage
  for t in claude git jq python3; do command -v "$t" >/dev/null 2>&1 || { echo "probe-anvil: $t not found" >&2; exit 2; }; done
  python3 -c 'import yaml' 2>/dev/null || { echo "probe-anvil: PyYAML not installed" >&2; exit 2; }
  plugin="$(cd "$plugin" && pwd -P)"
  mkdir -p "$out"; out="$(cd "$out" && pwd -P)"
  local scratch; scratch="$(mktemp -d "${TMPDIR:-/tmp}/probe-anvil.XXXXXX")"
  local project="$scratch/project"
  cp -R "$fixture" "$project"
  if [ -n "$dirty" ] && [ ! -f "$project/$dirty" ]; then mkdir -p "$(dirname "$project/$dirty")"; printf '# app\n' >"$project/$dirty"; fi
  ( cd "$project" && git init -q && git add -A && git -c user.name=probe -c user.email=probe@localhost commit -q -m "pre-build" ) || { echo "probe-anvil: fixture git init failed" >&2; exit 2; }
  [ -n "$dirty" ] && printf '# local edit, uncommitted\n' >>"$project/$dirty"

  local spec_rel
  spec_rel="$(cd "$project" && find .touchstone/epics -name '*.spec.yaml' | sort | head -1)"
  [ -n "$spec_rel" ] || { echo "probe-anvil: fixture carries no *.spec.yaml" >&2; exit 2; }
  python3 - "$project/$spec_rel" >"$out/source-paths.txt" <<'PY'
import sys, yaml
d = yaml.safe_load(open(sys.argv[1], encoding='utf-8'))
for p in (d.get('touch_set') or {}).get('touched') or []:
    print(str(p).split('#')[0].strip())
PY

  local plugin_used="$plugin" rev tree_state="clean"
  rev="$(git -C "$plugin" rev-parse HEAD 2>/dev/null || echo unknown)"
  shipped_surface_dirty "$plugin" && tree_state="dirty"
  if [ -n "$override" ]; then
    plugin_used="$scratch/plugin"
    git -C "$plugin" worktree add -q --detach "$plugin_used" HEAD || { echo "probe-anvil: worktree add failed" >&2; exit 2; }
    cp "$override" "$plugin_used/agents/ruler-author.md"
  fi
  { printf '%s\ntree: %s\n' "$rev" "$tree_state"; [ -n "$override" ] && printf 'override: agents/ruler-author.md replaced by %s\n' "$(basename "$(dirname "$override")")/$(basename "$override")"; } >"$out/plugin_revision.txt"
  : >"$out/events.jsonl"
  write_observer "$scratch/observe.sh" "$project" "$out" "$spec_rel" "$delete_freeze"
  local settings="$scratch/settings.json"
  jq -n --arg obs "$scratch/observe.sh" '{hooks:{PostToolUse:[{hooks:[{type:"command",command:("bash " + $obs)}]}]}}' >"$settings"

  local prompt="/touchstone:anvil $spec_rel"
  [ -n "$extra" ] && prompt="$prompt

$extra"
  local cmd; cmd="claude -p $(printf '%q' "$prompt") --plugin-dir $(printf '%q' "$plugin_used") --setting-sources project --settings $(printf '%q' "$settings") --permission-mode bypassPermissions --output-format stream-json --verbose --model $model --max-turns $turns --max-budget-usd $budget"
  printf '%s\n' "(cd $project && $cmd)" >"$out/command.txt"
  date -u +%Y-%m-%dT%H:%M:%SZ >"$out/started_at.txt"
  ( cd "$project" && eval "$cmd" ) >"$out/output.log" 2>&1
  local rc=$?
  mkdir -p "$out/artifacts"
  local epic; epic="$(dirname "$project/$spec_rel")"
  for f in ruler.yaml freeze.json verdict.yaml red-first.json disputes.yaml; do
    [ -f "$epic/build/$f" ] && cp "$epic/build/$f" "$out/artifacts/$f"
  done
  [ -d "$epic/build/ruler" ] && cp -R "$epic/build/ruler" "$out/artifacts/ruler"
  cp "$project/$spec_rel" "$out/artifacts/spec.yaml"
  [ -f "$epic/deviation.yaml" ] && cp "$epic/deviation.yaml" "$out/artifacts/deviation.yaml"
  ( cd "$project" && git status --porcelain ) >"$out/final-status.txt" 2>/dev/null
  jq -r 'select(.type=="result") | .total_cost_usd // empty' "$out/output.log" 2>/dev/null | tail -1 >"$out/cost.txt"
  printf 'claude exit: %s\n' "$rc" >>"$out/final-status.txt"
  [ -n "$override" ] && git -C "$plugin" worktree remove --force "$plugin_used" 2>/dev/null
  [ "$keep" -eq 1 ] || rm -rf "$scratch"
  echo "probe-anvil: run finished (claude exit $rc), evidence at $out"
  return 0
}

# ---------------------------------------------------------------- verify
cmd_verify() {
  local out="" expect="" plugin=""
  out="$1"; shift
  while [ $# -gt 0 ]; do
    case "$1" in
      --expect) expect="$2"; shift 2 ;;
      --plugin-dir) plugin="$2"; shift 2 ;;
      *) usage ;;
    esac
  done
  [ -d "$out" ] && [ -n "$expect" ] || usage
  [ -f "$out/events.jsonl" ] || { echo "probe-anvil: $out/events.jsonl missing" >&2; return 1; }
  local head_sha=""
  [ -n "$plugin" ] && head_sha="$(git -C "$plugin" rev-parse HEAD 2>/dev/null || true)"
  python3 - "$out" "$expect" "$head_sha" "${plugin:-.}" <<'PY'
import json, os, re, subprocess, sys
out, expect, head_sha = sys.argv[1], sys.argv[2], sys.argv[3]
plugin_dir = sys.argv[4] if len(sys.argv) > 4 else '.'
ev = [json.loads(l) for l in open(os.path.join(out, 'events.jsonl'), encoding='utf-8') if l.strip()]
source = 'observer'
if not ev:
    # the observer recorded nothing: derive the same event shape from the stream-json transcript —
    # one event per tool_use (main thread and sidechains), artifact presence inferred from the
    # tool that produced each artifact, source dirt from Write/Edit/heredoc targets
    source = 'transcript'
    srcs = [l.strip() for l in open(os.path.join(out, 'source-paths.txt'), encoding='utf-8')] if os.path.isfile(os.path.join(out, 'source-paths.txt')) else []
    ruler = freeze = verdict = disputes = False; dirty = set(); seq = 0
    pending = {}
    for line in open(os.path.join(out, 'output.log'), encoding='utf-8', errors='replace'):
        try: d = json.loads(line)
        except Exception: continue
        m = d.get('message') or {}
        for c in (m.get('content') or []) if isinstance(m.get('content'), list) else []:
            if not isinstance(c, dict): continue
            if c.get('type') == 'tool_use':
                inp = c.get('input') or {}; name = c.get('name') or ''
                fp = str(inp.get('file_path') or ''); cmd = str(inp.get('command') or ''); prompt = str(inp.get('prompt') or '')
                if fp.endswith('build/ruler.yaml') and name in ('Write', 'Edit'): ruler = True
                if name in ('Write', 'Edit') and any(fp.endswith('/' + s) or fp == s for s in srcs): dirty.add(fp)
                for s in srcs:
                    if re.search(r'>\s*[\'"]?(?:\./)?' + re.escape(s) + r'\b', cmd): dirty.add(s)
                markers = [k for k, pat in (('re-dispatch', 're-dispatch'), ('check-artifact', 'check-artifact'), ('rulings', 'rulings:')) if pat in prompt]
                seq += 1
                e = {'seq': seq, 'tool': name, 'agent': inp.get('subagent_type') or '', 'description': inp.get('description') or '', 'model': inp.get('model') or '',
                     'file_path': fp, 'prompt_markers': markers, 'ruler': ruler, 'freeze': freeze, 'verdict': verdict, 'disputes': disputes,
                     'freeze_deleted': False, 'spec_wn': 0, 'src_dirty': sorted(dirty), '_cmd': cmd}
                ev.append(e); pending[c.get('id')] = e
            elif c.get('type') == 'tool_result':
                e = pending.get(c.get('tool_use_id'))
                if not e: continue
                res = c.get('content'); text = res if isinstance(res, str) else json.dumps(res)
                if 'ruler.py' in e['_cmd'] and ' freeze' in e['_cmd'] and 'OK frozen' in text: freeze = True; e['freeze'] = True
                if 'held-out' in e['_cmd'] and 'verdict:' in text: verdict = True; e['verdict'] = True
                if 'freeze.json' in e['_cmd'] and ('rm ' in e['_cmd']) and 'freeze.json' in text: pass
                if 'disputes.yaml' in e['file_path']: disputes = True
    for e in ev: e.pop('_cmd', None)
def first(pred):
    for e in ev:
        if pred(e): return e['seq']
    return None
def rd(name):
    p = os.path.join(out, name)
    return open(p, encoding='utf-8', errors='replace').read() if os.path.isfile(p) else ''
s_ruler = first(lambda e: e.get('ruler'))
s_freeze = first(lambda e: e.get('freeze'))
s_src = first(lambda e: e.get('src_dirty'))
s_del = first(lambda e: e.get('freeze_deleted'))
dispatches = [e for e in ev if e.get('tool') == 'Agent' and ('ruler-author' in (e.get('agent') or '') or (e.get('description') or '') == 'ruler-author')]
art = lambda n: os.path.isfile(os.path.join(out, 'artifacts', n))
log = rd('output.log')
rev_lines = rd('plugin_revision.txt').splitlines()
fails = []
if expect == 'order':
    if s_ruler is None: fails.append('ruler.yaml never appeared')
    if s_freeze is None: fails.append('freeze.json never appeared')
    if s_ruler is not None and s_freeze is not None and not s_ruler < s_freeze:
        fails.append(f'out of order: freeze.json (seq {s_freeze}) before ruler.yaml (seq {s_ruler})')
    if s_src is not None and s_freeze is not None and not s_freeze < s_src:
        fails.append(f'out of order: source edit (seq {s_src}) before freeze.json (seq {s_freeze})')
    if s_src is not None and s_freeze is None:
        fails.append(f'out of order: source edit (seq {s_src}) with no freeze.json')
    if not art('verdict.yaml'): fails.append('verdict.yaml absent at hand-off')
    if head_sha:
        rev0 = rev_lines[0].strip() if rev_lines else ''
        anc = subprocess.run(['git', '-C', plugin_dir, 'merge-base', '--is-ancestor', rev0, 'HEAD'], capture_output=True).returncode == 0 if rev0 else False
        if not anc: fails.append(f'plugin_revision.txt {rev0!r} is not the checkout HEAD {head_sha} or an ancestor of it')
        if len(rev_lines) < 2 or rev_lines[1].strip() != 'tree: clean': fails.append(f'plugin_revision.txt tree line {rev_lines[1:2]!r} is not `tree: clean`')
elif expect == 'halt-freeze':
    if s_del is None: fails.append('freeze.json was never deleted by the observer')
    later = [e['seq'] for e in ev if s_del is not None and e['seq'] > s_del and e.get('src_dirty')]
    if later: fails.append(f'source path edited after the freeze deletion (seq {later[0]})')
    if art('verdict.yaml'): fails.append('verdict.yaml exists — the run did not halt')
    if 'freeze.json' not in log: fails.append('output.log never names freeze.json')
elif expect in ('silent-once', 'silent-twice', 'invalid-once'):
    if len(dispatches) != 2: fails.append(f'ruler-author dispatches: {len(dispatches)} (want 2)')
    if expect in ('silent-once', 'invalid-once'):
        if not art('ruler.yaml'): fails.append('ruler.yaml absent after the second dispatch')
        if not art('freeze.json'): fails.append('freeze.json absent — the run did not continue')
        if expect == 'invalid-once' and len(dispatches) == 2 and 'check-artifact' not in (dispatches[1].get('prompt_markers') or []):
            fails.append('the second dispatch prompt carries no check-artifact output')
    else:
        if art('freeze.json'): fails.append('freeze.json exists — the run did not halt')
        if 'ruler.yaml' not in log: fails.append('output.log never names ruler.yaml')
elif expect == 'overreach':
    dev = rd('artifacts/deviation.yaml')
    if not re.search(r'src/(helper|app)\.py', dev): fails.append('deviation.yaml carries no D-n naming the overreaching path')
    if not re.search(r'discard|remov|rm -rf', dev + log, re.IGNORECASE): fails.append('no record that the overreaching ruler was discarded')
    # an Agent event is logged when the dispatch returns, after its own tool events; the second
    # dispatch overstepped iff a source path was Written (the author has no Edit tool) between the
    # first and the second Agent event, or the session recorded a second D-n naming the path
    win = [d['seq'] for d in dispatches[:2]]
    authored = len(win) == 2 and any(
        e.get('tool') == 'Write' and re.search(r'src/(helper|app)\.py$', e.get('file_path') or '')
        and win[0] < e['seq'] <= win[1] for e in ev)
    recorded = len([blk for blk in re.split(r'(?m)^\s*- id: D-\d+', dev)[1:] if re.search(r'src/(helper|app)\.py', blk)]) >= 2
    second_violation = authored or recorded
    if second_violation and art('freeze.json'): fails.append('freeze.json exists — the second scope violation did not halt the run')
    if not second_violation and len(dispatches) == 2 and not art('freeze.json'): fails.append('the second dispatch stayed in scope yet the run did not continue to freeze')
    if len(dispatches) > 2: fails.append(f'ruler-author dispatches: {len(dispatches)} (want ≤ 2)')
elif expect == 'ambiguous':
    spec = rd('artifacts/spec.yaml'); dev = rd('artifacts/deviation.yaml'); ver = rd('artifacts/verdict.yaml')
    if not re.search(r'id:\s*W-\d+', spec) or 'AC-7' not in spec.split('waiting_on_human')[-1]: fails.append('spec waiting_on_human gained no W-n naming AC-7')
    if not art('freeze.json'): fails.append('freeze.json absent — freeze did not proceed past the ambiguity')
    if 'AC-7' not in dev or 'blocked' not in dev: fails.append('deviation.yaml carries no blocked D-n naming AC-7')
    m = re.search(r'- ac: AC-7\n\s+verdict: (\w+)\n\s+reason: (.*)', ver)
    if not m or m.group(1) != 'UNVERIFIED' or 'ambiguous' not in m.group(2): fails.append(f'verdict.yaml AC-7 is not UNVERIFIED reason ambiguous ({m.groups() if m else "row absent"})')
elif expect == 'guard':
    if 'guard-ruler:' not in log or 'is frozen' not in log: fails.append('output.log carries no guard-ruler block message')
    ver = rd('artifacts/verdict.yaml')
    if 'sha_check: ok' not in ver: fails.append('verdict.yaml sha_check is not ok')
else:
    print(f'probe-anvil: unknown --expect {expect}', file=sys.stderr); sys.exit(2)
for f in fails: print(f'FAIL {f}')
print(f'probe-anvil verify {expect}: ' + ('ok' if not fails else f'{len(fails)} failure(s)') +
      f' (ruler seq {s_ruler}, freeze seq {s_freeze}, first source edit seq {s_src}, dispatches {len(dispatches)}, events from the {source})')
sys.exit(1 if fails else 0)
PY
}

# ---------------------------------------------------------------- self-test
cmd_self_test() {
  local t; t="$(mktemp -d "${TMPDIR:-/tmp}/probe-anvil-selftest.XXXXXX")"
  local good="$t/good" bad="$t/bad" rc=0 out
  mkdir -p "$good/artifacts" "$bad/artifacts"
  printf '%s\n' \
    '{"seq":1,"tool":"Bash","agent":"","description":"","ruler":false,"freeze":false,"verdict":false,"freeze_deleted":false,"src_dirty":[]}' \
    '{"seq":2,"tool":"Agent","agent":"touchstone:ruler-author","description":"ruler-author","ruler":true,"freeze":false,"verdict":false,"freeze_deleted":false,"src_dirty":[]}' \
    '{"seq":3,"tool":"Bash","agent":"","description":"","ruler":true,"freeze":true,"verdict":false,"freeze_deleted":false,"src_dirty":[]}' \
    '{"seq":4,"tool":"Write","agent":"","description":"","ruler":true,"freeze":true,"verdict":false,"freeze_deleted":false,"src_dirty":["src/greet.py"]}' \
    '{"seq":5,"tool":"Bash","agent":"","description":"","ruler":true,"freeze":true,"verdict":true,"freeze_deleted":false,"src_dirty":["src/greet.py"]}' >"$good/events.jsonl"
  : >"$good/artifacts/verdict.yaml"; : >"$good/output.log"
  printf '%s\n' \
    '{"seq":1,"tool":"Agent","agent":"touchstone:ruler-author","description":"ruler-author","ruler":true,"freeze":false,"verdict":false,"freeze_deleted":false,"src_dirty":[]}' \
    '{"seq":2,"tool":"Write","agent":"","description":"","ruler":true,"freeze":false,"verdict":false,"freeze_deleted":false,"src_dirty":["src/greet.py"]}' \
    '{"seq":3,"tool":"Bash","agent":"","description":"","ruler":true,"freeze":true,"verdict":true,"freeze_deleted":false,"src_dirty":["src/greet.py"]}' >"$bad/events.jsonl"
  : >"$bad/artifacts/verdict.yaml"; : >"$bad/output.log"
  if out="$(cmd_verify "$good" --expect order 2>&1)"; then echo "PASS: probe-anvil self-test valid order verifies"; else echo "FAIL: probe-anvil self-test valid order: $out"; rc=1; fi
  if out="$(cmd_verify "$bad" --expect order 2>&1)"; then echo "FAIL: probe-anvil self-test bad order verified as ok"; rc=1
  elif printf '%s' "$out" | grep -q 'out of order: source edit'; then echo "PASS: probe-anvil self-test out-of-order tree rejected, naming the source edit before freeze.json"
  else echo "FAIL: probe-anvil self-test bad order did not name the artifact: $out"; rc=1; fi
  rm -rf "$t"
  return "$rc"
}

case "${1:-}" in
  run) shift; cmd_run "$@" ;;
  verify) shift; cmd_verify "$@" ;;
  --self-test) cmd_self_test ;;
  *) usage ;;
esac
